default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') %>
  database: <%= ENV.fetch('MYSQL_DATABASE') %>
  host: <%= ENV.fetch('MYSQL_HOST') %>
  socket: <%= ENV.fetch('MYSQL_SOCKET') %>

development:
  <<: *default

test:
  <<: *default
  database: webapp_test
  host: db

production:
  <<: *default



